version: "3"
services:
  db:
    image: mysql 
    volumes:
      - /usr/local/dockerdata/cen_db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=admin"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
  web:
    build: ./web
    restart: always
    environment:
      - "VIRTUAL_HOST=katyl.info"
      - "LETSENCRYPT_HOST=katyl.info"
      - "LETSENCRYPT_EMAIL=katyl@atyl.info"
    ports: 
      - 80:80
